### PR TITLE
General fixes and improvements

### PR DESCRIPTION
**Pull request by felixmr1**
- fix(SubscribeState): add the path to the recieved chan type
- fix(PrimaryConnection): use ActiveConnection type
- feat(AccessPoint): add LastSeen property
- fix(DeviceWireless): remove duplicated fields
- fix(examples): move examples to their own subfolders

### CODE REVIEW

**Comment by felixmr1** [comment]
@mullerch I'm gathering all my changes here instead of opening separate PRs.

**Comment by felixmr1** [comment]
if this PR is accepted, then I will reverse to a1ddfea

**Comment by mullerch** [comment]
Please check the import paths, they are not targeting the correct repository.

**Comment by felixmr1** [comment]
@mullerch Yes that is due to 9dd5f1667d089a52c1f2079d93a5dc3083cb464c I was not sure if you had the time to review, so I had to move preemptively to get this to work with an internal repo. Please let me know if you request code changes, if so then I will revert to a1ddfeaa9c6eae49351ad1c767870e945db28cfd!

**Comment by mullerch** [comment]
You should do the PR on a branch, not your master so you can add only necessary changes and I can merge independently.

**Comment by felixmr1** [comment]
@mullerch should be fixed now!

**Review by mullerch — APPROVED** [review]

**Pull request merged**
